NumPy

In [2]:
import numpy as np
print(np.__version__)

1.15.4


Typy danych

In [2]:
l=[1,'2',True,3.0,None]

In [4]:
[type(item) for item in l]

[int, str, bool, float, NoneType]

In [5]:
np.array([4.1,0,1,2,3])

array([4.1, 0. , 1. , 2. , 3. ])

In [8]:
np.array([range(i, i+3) 
         for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Sposób tworzenia tablicy

In [10]:
#tablica wypelniona zerami
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
#tablica wypelniona 1
np.ones((5,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#tablica wypelniona ciagiem liniowym
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
#tablica wypelniona losowymi
np.random.normal(0,1,(3,3))

array([[ 0.8547271 , -1.06168882, -0.18313828],
       [-1.28074999, -0.36491435, -0.89853483],
       [ 0.69193114, -1.09260805,  1.31847209]])

In [19]:
#tablica wypelniona losowymi calkowitymi
np.random.randint(0,10,(3,3))

array([[6, 4, 6],
       [4, 1, 0],
       [4, 2, 5]])

Operowanie na tablicach w NumPy

In [31]:
x = np.random.randint(0,100, size = (2,3,4))
x

array([[[41, 33, 17, 27],
        [54, 33, 36, 77],
        [61, 16, 32,  2]],

       [[96, 18, 39, 25],
        [ 7, 73, 12, 56],
        [ 2, 68, 75, 65]]])

In [26]:
print(f"liczba wymiarow: {x.ndim}")
print(f"wymiary tabl: {x.shape}")
print(f"rozmiar tablicy: {x.size}")


liczba wymiarow: 3
liczba wymiarow: (2, 3, 4)
liczba wymiarow: 24


In [27]:
print(f"typ danych w  tablicy: {x.dtype}")

typ danych w  tablicy: int32


In [29]:
y= np.arange(0,10)

In [30]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
y[5]

5

In [32]:
y[2:5]

array([2, 3, 4])

In [32]:
x[0,1,2]

36

In [34]:
x[0,1,2] = 62

In [35]:
x

array([[[41, 65, 14, 14],
        [85, 35, 62, 43],
        [12, 75, 48, 59]],

       [[49, 97, 88, 24],
        [62, 53, 73, 32],
        [98,  9, 15,  2]]])

In [36]:
x[:1, :, :3]

array([[[41, 65, 14],
        [85, 35, 62],
        [12, 75, 48]]])

In [38]:
l1=[1,2,3]
l2 = l1[2:]
l2[0] = 4

In [39]:
l2

[4]

In [40]:
x = np.zeros((2,3))

In [41]:
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
y[0]=1

In [44]:
x_copy=x[:2, :2].copy()

Zmiana wymiarow

In [45]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
x = np.array([1,2,3])

In [49]:
x

array([1, 2, 3])

In [50]:
x.reshape((1,3))

array([[1, 2, 3]])

In [51]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

Laczenie tablic

In [54]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [55]:
np.concatenate([y,x])

array([3, 2, 1, 1, 2, 3])

In [54]:
grid = np.array([[1, 2, 3]
,[4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([grid,grid], axis = 0)
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([grid,grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
np.vstack([x,grid])

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [62]:
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [63]:
x =  np.arange(10)
print(x)
np.split(x,[3,5])

[0 1 2 3 4 5 6 7 8 9]


[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

Wykonywanie obliczen

In [65]:
#Funkcja ktora przyjmie liste liczb i zwroci liste z odwrotnosciami tych liczb

In [70]:
def compute(values):
    output = np.empty(len(values))
    for i, value in enumerate(values):
        output[i] = 1.0 / value
    return output

In [71]:
values = np.random.randint(1,10, size = 5)
print(values)
compute(values)

[5 5 7 5 6]


array([0.2       , 0.2       , 0.14285714, 0.2       , 0.16666667])

In [72]:
big_array = np.random.randint(1,100,size = 1_000_000)

In [73]:
%timeit compute(big_array)

2.58 s ± 44.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [75]:
%timeit 1.0 / big_array

4.33 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [76]:
1.0/ big_array

array([0.01449275, 0.01754386, 0.02380952, ..., 0.01538462, 0.01111111,
       0.01369863])

In [77]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
x * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [79]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [80]:
x + x 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##agregacja na tablicach

In [81]:
L = np.random.random(100)

In [82]:
print(np.sum(L))

52.44074085455967


In [83]:
print(np.min(L))

0.05118479642682927


In [84]:
print(np.max(L))

0.9981817417850793


In [85]:
M = np.random.randint(10, size = (3,4))

In [86]:
M

array([[7, 0, 6, 4],
       [1, 6, 4, 6],
       [0, 4, 6, 2]])

In [88]:
M.sum(axis=0)
#suma pionowo

array([ 8, 10, 16, 12])

In [90]:
M.sum(axis=1)
#suma poziomo

array([17, 17, 12])

##Porównanie tablic, maski

In [99]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [93]:
x<3, x> 3, x ==3, x >4

(array([ True,  True, False, False, False]),
 array([False, False, False,  True,  True]),
 array([False, False,  True, False, False]),
 array([False, False, False, False,  True]))

In [100]:
x = np.random.randint(10, size =(4,4))
x

array([[1, 7, 0, 3],
       [6, 6, 2, 0],
       [5, 9, 7, 9],
       [9, 8, 3, 4]])

In [97]:
(x<6).sum()
np.count_nonzero(x<6)

8

In [101]:
np.sum(x<6, axis =1)
#liczy tru i false, ktore traktuje jako 0 i 1

array([3, 2, 1, 2])

In [109]:
x[x<5] = 0 

In [110]:
x

array([[0, 7, 0, 0],
       [6, 6, 0, 0],
       [5, 9, 7, 9],
       [9, 8, 0, 0]])

Fancy indexing

In [111]:
x = np.random.randint(100, size = 10)
x

array([11, 73, 54, 54,  7, 46, 15,  3, 48, 22])

In [112]:
#wyciagnij 3,7 i 2 elem

In [117]:
np.array([x[2],x[6],x[1]])

array([54, 15, 73])

In [114]:
ind = [2,6,1]

In [115]:
x[ind]


array([54, 15, 73])

In [116]:
x[[2,6,1]]

array([54, 15, 73])

In [119]:
ind = np.array([[3,7],
               
[4,5]])
x[ind]

array([[54,  3],
       [ 7, 46]])

In [120]:
x = np.random.randint(100, size = (5,5))

In [121]:
x

array([[60, 24, 96, 22, 65],
       [ 4, 26, 78,  7, 22],
       [20, 12, 77, 24, 37],
       [51, 55, 95, 66, 59],
       [18, 49, 72, 72, 18]])

In [122]:
x[2,[0,1,2]]
#fancy indexing

array([20, 12, 77])

In [123]:
x[1:,[2,0,1]]
#fancy indexing

array([[78,  4, 26],
       [77, 20, 12],
       [95, 51, 55],
       [72, 18, 49]])

Sortowanie tablic

In [133]:
x = np.random.randint(100, size = (5))

In [134]:
x

array([19, 79, 29, 80, 80])

In [135]:
np.sort(x)

array([19, 29, 79, 80, 80])

In [136]:
i = np.argsort(x)
i

array([0, 2, 1, 3, 4], dtype=int64)

In [137]:
x[i]

array([19, 29, 79, 80, 80])

In [138]:
#1. Wygeneruj tablicę 100 liczb całkowitych od 0 do 10 i wybierz z niej elementy nieparzyste.

In [152]:
x = np.random.randint(10, size = (100))

In [153]:
x

array([8, 3, 7, 3, 2, 2, 7, 1, 5, 0, 7, 5, 7, 0, 4, 6, 0, 9, 7, 1, 6, 2,
       8, 2, 4, 4, 4, 1, 1, 7, 7, 6, 1, 5, 0, 9, 9, 7, 9, 7, 6, 3, 3, 5,
       0, 2, 3, 6, 8, 8, 5, 4, 7, 2, 8, 4, 8, 2, 3, 2, 2, 1, 6, 4, 9, 9,
       2, 2, 1, 2, 9, 2, 8, 5, 9, 5, 2, 1, 7, 0, 4, 2, 6, 9, 4, 2, 4, 0,
       3, 6, 4, 4, 9, 1, 5, 2, 4, 8, 6, 2])

In [154]:
x%2==0

array([ True, False, False, False,  True,  True, False, False, False,
        True, False, False, False,  True,  True,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True, False, False,  True,  True, False,  True, False,  True,
        True, False, False, False,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
        True])

In [157]:
x[x%2!=0]=0
x

array([8, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 4, 6, 0, 0, 0, 0, 6, 2,
       8, 2, 4, 4, 4, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0,
       0, 2, 0, 6, 8, 8, 0, 4, 0, 2, 8, 4, 8, 2, 0, 2, 2, 0, 6, 4, 0, 0,
       2, 2, 0, 2, 0, 2, 8, 0, 0, 0, 2, 0, 0, 0, 4, 2, 6, 0, 4, 2, 4, 0,
       0, 6, 4, 4, 0, 0, 0, 2, 4, 8, 6, 2])

In [144]:
#2. Korzystając z tablicy z poprzedniego zadania zastąp elementy nieparzyste zerami.


In [164]:
x = np.random.randint(10, size = (100))
x_copy=x.copy()
x_copy[x%2!=0]=0
x_copy, x


(array([0, 0, 0, 0, 2, 6, 6, 2, 6, 0, 4, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 0, 8, 0, 4, 0, 0, 0, 0, 6, 8, 0, 2, 8, 0, 0, 0, 0, 0,
        0, 4, 0, 8, 6, 0, 2, 4, 0, 2, 0, 2, 0, 6, 0, 6, 0, 4, 8, 0, 8, 0,
        2, 0, 2, 2, 4, 0, 0, 4, 0, 0, 4, 0, 4, 0, 4, 0, 6, 4, 6, 0, 8, 4,
        6, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 6]),
 array([5, 5, 9, 3, 2, 6, 6, 2, 6, 9, 4, 3, 1, 7, 0, 4, 7, 7, 0, 1, 3, 9,
        1, 7, 7, 2, 9, 8, 7, 4, 0, 1, 5, 3, 6, 8, 0, 2, 8, 1, 7, 7, 5, 7,
        0, 4, 7, 8, 6, 9, 2, 4, 3, 2, 7, 2, 9, 6, 7, 6, 5, 4, 8, 3, 8, 5,
        2, 1, 2, 2, 4, 3, 3, 4, 3, 3, 4, 1, 4, 0, 4, 7, 6, 4, 6, 9, 8, 4,
        6, 6, 2, 3, 3, 7, 7, 0, 3, 9, 3, 6]))

In [166]:
#4. Z tablicy z poprzedniego zadania wybrać elementy większe niż 20 i mniejsze niż 50


In [174]:
x = np.random.randint(100, size = (100))
x[(x>20) & (x<60)]

array([35, 28, 28, 35, 24, 37, 28, 29, 48, 43, 31, 42, 25, 37, 54, 42, 39,
       34, 33, 44, 57, 43, 48, 44, 57, 29, 28, 26, 42, 59, 51, 48, 43, 52,
       57, 53, 40, 37, 51])

In [175]:
# 5. Wygeneruj tablicę o wymiarach 10x10 i stwórz nową tablicę, która ma odwróconą kolejność wierszy.

In [176]:
x = np.random.randint(100, size = (10,10))

In [177]:
x

array([[96, 69, 69,  4, 92, 80, 12,  9, 94, 63],
       [52,  3, 70, 78, 25, 11, 97, 19, 35, 83],
       [78, 96, 97, 12, 54, 20, 10, 25, 48, 85],
       [26, 27, 72, 40, 24,  9, 26, 62,  3, 56],
       [83, 65, 78, 21, 54, 97, 41, 93, 54, 13],
       [ 6,  6, 94, 44, 98, 70, 60, 88, 22, 15],
       [87, 93, 53, 71,  1, 48, 86, 31, 36, 26],
       [55, 49, 72, 70, 46, 33, 17, 40, 97, 57],
       [86, 20, 85,  8, 36, 70, 70, 61, 99, 90],
       [22, 70,  3, 76, 54, 45, 69, 80, 66, 50]])

In [180]:
x_inverse = x[:,::-1]
x_inverse

array([[63, 94,  9, 12, 80, 92,  4, 69, 69, 96],
       [83, 35, 19, 97, 11, 25, 78, 70,  3, 52],
       [85, 48, 25, 10, 20, 54, 12, 97, 96, 78],
       [56,  3, 62, 26,  9, 24, 40, 72, 27, 26],
       [13, 54, 93, 41, 97, 54, 21, 78, 65, 83],
       [15, 22, 88, 60, 70, 98, 44, 94,  6,  6],
       [26, 36, 31, 86, 48,  1, 71, 53, 93, 87],
       [57, 97, 40, 17, 33, 46, 70, 72, 49, 55],
       [90, 99, 61, 70, 70, 36,  8, 85, 20, 86],
       [50, 66, 80, 69, 45, 54, 76,  3, 70, 22]])

In [8]:
np.array([range(i, i+1) 
         for i in [1,2,3]])

array([[1],
       [2],
       [3]])

In [11]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [23]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [35]:
x = np.zeros((3, 4, 5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [36]:
y = np.moveaxis(x, -1, 0)

In [37]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
np.random.normal(0,2,(3,3))

array([[-0.47772492,  3.10093506, -0.53771082],
       [ 2.75183148,  2.6511135 , -1.612234  ],
       [-1.49668308,  0.73489889, -0.73090961]])

In [44]:
np.random.normal(0,1,(3,5,7))

array([[[ 0.64970317,  0.03319241,  0.37364266,  0.71436295,
          0.8201147 ,  0.24703141,  0.99575175],
        [ 0.37374733,  1.08967242,  0.47095371,  0.08368722,
         -0.82740412, -0.51672827,  1.18588057],
        [-0.57715527,  1.77983142, -0.15972352,  0.63139509,
          0.24342623,  0.44726991, -0.39289709],
        [ 0.0804593 , -0.21960853, -0.64838214, -0.42741817,
          0.38486815,  0.50234493, -0.3666975 ],
        [ 2.49079113,  3.34041596, -1.39662458,  1.69399482,
         -1.2262474 ,  1.90590647, -0.74762956]],

       [[ 2.17974014,  0.92647963, -1.48804925, -0.42341739,
          1.24569236,  0.2819224 ,  0.31461929],
        [-1.85120239, -0.71512359, -0.23534566,  0.121534  ,
         -2.46978381,  0.56152112,  0.05158966],
        [ 0.93543311,  0.58242117,  0.63943232, -0.39204319,
         -0.32631703, -0.17011406, -0.39327367],
        [ 0.75851156, -0.07865092,  0.48310096, -0.91881739,
          0.8221991 ,  0.47173088,  1.04012742],
        

In [50]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])
  
gfg = np.concatenate((arr1, arr2), axis = 1)
  
print (gfg)

[[2 4 3 5]
 [6 8 7 9]]


In [51]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])
  
gfg = np.concatenate((arr1, arr2), axis = 0)
  
print (gfg)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]
