In [2]:
import pandas as pd
import numpy as np

In [8]:
#SERIES - Jednowymiarowa tablica z indeksem
data = pd.Series([0.25,0.5,0.75,1.0])
index = ['a', 'b','c','d']
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
print(data.index)

RangeIndex(start=0, stop=4, step=1)


In [5]:
print(data.values)

[0.25 0.5  0.75 1.  ]


In [6]:
type(data.values)

numpy.ndarray

In [12]:
d = {'a':0, 'b':1}
print(d['b'])


1


In [18]:
population_dict = {'California': 2232322232,
             'TexAS': 121212434,
             'New York': 4667745353}
poopulation = pd.Series(population_dict)

In [19]:
population

{'California': 2232322232, 'TexAS': 121212434, 'nEW yORK': 4667745353}

In [21]:
population['California': 'New York']

TypeError: unhashable type: 'slice'

In [23]:
series = [pd.Series([2,4,6]),
          pd.Series(5, index = [2,4,6]),
          pd.Series(2: 'a', 3: 'b'),
          pd.Series(np.arrange(10))
        
]
for serie in series:
    print(serie)

SyntaxError: invalid syntax (Temp/ipykernel_18308/1191371984.py, line 3)

In [24]:
# Data FRAMe

In [25]:
population_dict = {'California': 2232322232,
             'TexAS': 121212434,
             'New York': 4667745353}
population = pd.Series(population_dict)
area_dict = {'California': 21211,
             'TexAS': 98989898,
             'New York': 343333}
area = pd.Series(area_dict)

In [26]:
area

California       21211
TexAS         98989898
New York        343333
dtype: int64

In [27]:
population

California    2232322232
TexAS          121212434
New York      4667745353
dtype: int64

In [28]:
states = pd.DataFrame({'population':population,
                      'area':area})

In [29]:
states

population      area
California  2232322232     21211
TexAS        121212434  98989898
New York    4667745353    343333

In [32]:
states.index 


Index(['California', 'TexAS', 'New York'], dtype='object')

In [31]:
states.columns

Index(['population', 'area'], dtype='object')

In [33]:
#Jak stworzyć obiekt DataFrame?

In [34]:
data = [{'a' = i, 'b': 2 * i}
       for i in range(3)]
dfs = [
    pd.DataFrame(population, columns=['population']),
    pd.DataFrame(data),
    pd.DataFrame({'population': population,
                           'area': area}),
    pd.DataFrame(np.random.rand(3, 2),
                 columns=['foo', 'bar'],
                 index=['a', 'b', 'c'])
]

for df in dfs:
    print()


SyntaxError: invalid syntax (Temp/ipykernel_18308/832494884.py, line 1)

In [37]:
ind = pd.Index([2,3,5,6,7,11], dtype = 'int64')

In [40]:
data = pd.Series(['a', 'b','c'], index = [1,3,5])

In [41]:
data[1] #indeks Series

'a'

In [43]:
data[1:3] #indeks z numpy

3    b
5    c
dtype: object

In [44]:
#loc indeks Series  iloc indeks Numpy

In [45]:
data.loc[1]

'a'

In [46]:
data.loc[1:3]

1    a
3    b
dtype: object

In [47]:
data.iloc[1]

'b'

In [48]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [49]:
#wybieranie danych DataFrame

states = pd.DataFrame({'population':population,
                      'area':area})

In [50]:
states['area']

California       21211
TexAS         98989898
New York        343333
Name: area, dtype: int64

In [66]:
states['density'] = states['population'] / states['area']

In [ ]:
states['de']

In [61]:
states

population      area         dnsity        density
California  2232322232     21211  105243.610957  105243.610957
TexAS        121212434  98989898       1.224493       1.224493
New York    4667745353    343333   13595.388014   13595.388014

In [62]:
#Korzystanie z DataFRame jako dużej tablicy numpy

In [64]:
states.iloc[:2,:2]

population      area
California  2232322232     21211
TexAS        121212434  98989898

In [67]:
states.loc[:'Texas', :'population']

KeyError: 'Texas'

In [69]:
filtr = states['density'] > 100

In [71]:
states.loc[filtr, ['population', 'area']]

population    area
California  2232322232   21211
New York    4667745353  343333

In [72]:
states

population      area         dnsity        density
California  2232322232     21211  105243.610957  105243.610957
TexAS        121212434  98989898       1.224493       1.224493
New York    4667745353    343333   13595.388014   13595.388014

In [73]:
states.iloc[0,2] = 90

In [74]:
states

population      area        dnsity        density
California  2232322232     21211     90.000000  105243.610957
TexAS        121212434  98989898      1.224493       1.224493
New York    4667745353    343333  13595.388014   13595.388014

In [75]:
## Operowanie na brakujących danych

In [77]:
type (None) #singeltone

NoneType

In [80]:
vals1=np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [81]:
vals2 = np.array([1,3,4])
vals2

array([1, 3, 4])

In [82]:
class A:
    a =3

In [83]:
vals3 = np.array([1,2,A(),4])
vals3

array([1, 2, <__main__.A object at 0x000001FFB60012E0>, 4], dtype=object)

In [86]:
for dtype in ['object', 'int']:
    print(f'dtype = [dtype]')
    %timeit np.array(1E6, dtype = dtype).sum()
    print()

dtype = [dtype]
2.73 µs ± 100 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

dtype = [dtype]
2.76 µs ± 45.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)



In [87]:
#NaN = not a number

In [88]:
vals2 = np.array([1,np.nan,3,4])
vals2

array([ 1., nan,  3.,  4.])

In [89]:
vals2.dtype

dtype('float64')

In [90]:
vals2 + 3 

array([ 4., nan,  6.,  7.])

In [91]:
vals2.sum()

nan

In [97]:
np.nansum(vals2),
np.nanmin(vals2),
np.nanmax(vals2)

4.0

In [99]:
#Nan i None w pandas

In [102]:
s = pd.Series([1,np.nan,2,None])

In [103]:
s.sum()

3.0

In [104]:
data = pd.Series([1,np.nan,2,None])

In [105]:
data.dropna()

0    1.0
2    2.0
dtype: float64

In [107]:
data.fillna(0)

0    1.0
1    0.0
2    2.0
3    0.0
dtype: float64

In [109]:
data[data.notnull()]

0    1.0
2    2.0
dtype: float64

In [110]:
### Łączenie danych

In [111]:
ser1 = pd.Series(['A','B','C'], index = [1,2,3])
ser2 = pd.Series(['D','E','F'], index = [4,5,6])

In [112]:
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [122]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

In [123]:
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [124]:
df1.append(df2)

NameError: name 'df1' is not defined

In [133]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue', 'Asia'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR', 'Tester']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

In [126]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [137]:
df1


employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4     Asia       Tester

In [138]:
df3 = pd.merge(df1,df2, on = 'employee')

In [139]:
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [140]:
df3[df3.hire_date.isnull()]

Empty DataFrame
Columns: [employee, group, hire_date]
Index: []

In [141]:
df1 = make_df('AB', [1, 2, 4])
df2 = make_df('ABCD', [1, 2, 5, 6])

df1

df2

for how in ('left', 'right', 'outer', 'inner'):
    print(f'df1 {how} join df2')
    print(pd.merge(df1, df2, on='A', how=how))
    print('-'*10)

df1 left join df2
    A B_x  B_y    C    D
0  A1  B1   B1   C1   D1
1  A2  B2   B2   C2   D2
2  A4  B4  NaN  NaN  NaN
----------
df1 right join df2
    A  B_x B_y   C   D
0  A1   B1  B1  C1  D1
1  A2   B2  B2  C2  D2
2  A5  NaN  B5  C5  D5
3  A6  NaN  B6  C6  D6
----------
df1 outer join df2
    A  B_x  B_y    C    D
0  A1   B1   B1   C1   D1
1  A2   B2   B2   C2   D2
2  A4   B4  NaN  NaN  NaN
3  A5  NaN   B5   C5   D5
4  A6  NaN   B6   C6   D6
----------
df1 inner join df2
    A B_x B_y   C   D
0  A1  B1  B1  C1  D1
1  A2  B2  B2  C2  D2
----------


In [142]:
#agregacje i grupowanie

In [146]:
df = pd.DataFrame({'A': [1,2,3]})
df.mean()

A    2.0
dtype: float64

In [147]:
df.count()

A    3
dtype: int64

In [149]:
df = pd.DataFrame({'key':['A','B','C','A','B','C'],
                  'data': range(6) })

In [152]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [153]:
df.groupby('key')[['data']].median()

data
key      
A     1.5
B     2.5
C     3.5